[workspace]
members = ["crates/*", "examples/counter"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false
repository = "https://github.com/lxcid/netplaycraft"

[workspace.dependencies]
netplaycraft-core = { path = "crates/netplaycraft-core" }
netplaycraft-sim = { path = "crates/netplaycraft-sim" }
netplaycraft-transport = { path = "crates/netplaycraft-transport" }
netplaycraft-transport-memory = { path = "crates/netplaycraft-transport-memory" }

[workspace.lints.rust]
unsafe_code = "forbid"
